In [1]:
!pip install pyspark pandas requests sqlalchemy pymysql matplotlib

Requirement already satisfied: pyspark in c:\users\lenovo\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (4.1.1)
Requirement already satisfied: pandas in c:\users\lenovo\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (3.0.3)
Requirement already satisfied: requests in c:\users\lenovo\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (2.34.2)
Requirement already satisfied: sqlalchemy in c:\users\lenovo\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (2.0.49)
Requirement already satisfied: pymysql in c:\users\lenovo\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (1.2.0)
Requirement already satisfied: matplotlib in c:\users\lenovo\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (3.10.9)
Requirement already satisfied: py4j<0.10.9.10,>=0.10.9.7 in c:\users\lenovo\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pyspark) (0.10.9.9)
Requirement already satisfied: numpy>=1.26.0 in c:\users\lenovo\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandas) (2.1.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\lenovo\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\lenovo\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandas) (2024.1)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\lenovo\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from requests) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in c:\users\lenovo\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from requests) (3.15)
Requirement already satisfied: urllib3<3,>=1.26 in c:\users\lenovo\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from requests) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in c:\users\lenovo\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from requests) (2026.5.20)
Requirement already satisfied: greenlet>=1 in c:\users\lenovo\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from sqlalchemy) (3.5.1)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\lenovo\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from sqlalchemy) (4.9.0)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\lenovo\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\lenovo\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\lenovo\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from matplotlib) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\lenovo\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: packaging>=20.0 in c:\users\lenovo\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from matplotlib) (24.1)
Requirement already satisfied: pillow>=8 in c:\users\lenovo\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from matplotlib) (10.4.0)
Requirement already satisfied: pyparsing>=3 in c:\users\lenovo\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: six>=1.5 in c:\users\lenovo\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

[notice] A new release of pip is available: 24.0 -> 26.1.1
[notice] To update, run: C:\Users\Lenovo\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [22]:
import requests
import json
import pandas as pd
import matplotlib.pyplot as plt

from sqlalchemy import create_engine
from pyspark.sql import SparkSession

In [23]:
spark = SparkSession.builder \
    .appName("VideoGames-MultiSource-ETL") \
    .getOrCreate()

In [24]:
API_KEY = "2ec9b9a5188841d59822585a112d749f"

url = f"https://api.rawg.io/api/games?key={API_KEY}"

response = requests.get(url)

print(f"Status Code: {response.status_code}")

api_data = response.json()

print(f"✅ Datos obtenidos de la API")
print(f"Keys disponibles: {api_data.keys()}")

Status Code: 200
✅ Datos obtenidos de la API
Keys disponibles: dict_keys(['count', 'next', 'previous', 'results', 'seo_title', 'seo_description', 'seo_keywords', 'seo_h1', 'noindex', 'nofollow', 'description', 'filters', 'nofollow_collections'])

In [25]:
api_games = api_data["results"]

api_df = pd.DataFrame(api_games)

api_df = api_df[
    [
        "id",
        "name",
        "released",
        "rating",
        "metacritic"
    ]
]

api_df.head()

     id                              name    released  rating  metacritic
0  3498                Grand Theft Auto V  2013-09-17    4.47          92
1  3328          The Witcher 3: Wild Hunt  2015-05-18    4.64          92
2  4200                          Portal 2  2011-04-18    4.58          95
3  4291  Counter-Strike: Global Offensive  2012-08-21    3.57          81
4  5286                       Tomb Raider  2013-03-05    4.06          86

In [26]:
spark_api_df = spark.createDataFrame(api_df)

spark_api_df.show(5)

+----+--------------------+----------+------+----------+
|  id|                name|  released|rating|metacritic|
+----+--------------------+----------+------+----------+
|3498|  Grand Theft Auto V|2013-09-17|  4.47|        92|
|3328|The Witcher 3: Wi...|2015-05-18|  4.64|        92|
|4200|            Portal 2|2011-04-18|  4.58|        95|
|4291|Counter-Strike: G...|2012-08-21|  3.57|        81|
|5286|         Tomb Raider|2013-03-05|  4.06|        86|
+----+--------------------+----------+------+----------+
only showing top 5 rows

In [27]:
import pymysql

try:
    conn = pymysql.connect(
        host='127.0.0.1',
        user='root',
        password='',
        database='historical_events_db'
    )
    print('✅ Conectado directamente con PyMySQL')
    conn.close()
except Exception as e:
    print(f'❌ Error: {e}')

❌ Error: (1045, "Access denied for user 'root'@'localhost' (using password: NO)")

In [28]:
# Cadena de conexión correcta para MariaDB sin contraseña
# Formato: mysql+pymysql://usuario:contraseña@host:puerto/base_de_datos
engine = create_engine(
    "mysql+pymysql://root:@127.0.0.1:3307/historical_events_db"
)

with engine.connect() as connection:
    db_df = pd.read_sql(
        "SELECT * FROM historical_events",
        connection
    )

print(f"✅ Leídos {len(db_df)} registros desde MariaDB")
db_df.head()

✅ Leídos 25 registros desde MariaDB

   id             event_name  year  country    category  importance_score
0   1      French Revolution  1789   France  Revolution               9.8
1   2           Moon Landing  1969      USA       Space              10.0
2   3    Fall of Berlin Wall  1989  Germany    Politics               9.5
3   4  Industrial Revolution  1760  England    Industry               9.7
4   5           World War II  1939   Global         War              10.0

In [29]:
spark_db_df = spark.createDataFrame(db_df)
spark_db_df.show()

+---+--------------------+----+---------------+-----------+----------------+
| id|          event_name|year|        country|   category|importance_score|
+---+--------------------+----+---------------+-----------+----------------+
|  1|   French Revolution|1789|         France| Revolution|             9.8|
|  2|        Moon Landing|1969|            USA|      Space|            10.0|
|  3| Fall of Berlin Wall|1989|        Germany|   Politics|             9.5|
|  4|Industrial Revolu...|1760|        England|   Industry|             9.7|
|  5|        World War II|1939|         Global|        War|            10.0|
|  6|Fall of the Roman...| 476|          Italy|     Empire|             9.8|
|  7|Discovery of Amer...|1492|          Spain|Exploration|             9.7|
|  8|   French Revolution|1789|         France| Revolution|             9.9|
|  9|American Declarat...|1776|  United States|   Politics|             9.5|
| 10|Industrial Revolu...|1760| United Kingdom| Technology|             9.8|
| 11|  World War I Begins|1914|Austria-Hungary|        War|             9.6|
| 12|   World War II Ends|1945|        Germany|        War|            10.0|
| 13|Moon Landing Apol...|1969|  United States|    Science|             9.7|
| 14|Fall of the Berli...|1989|        Germany|   Politics|             9.4|
| 15|Signing of the Ma...|1215| United Kingdom|        Law|             9.2|
| 16|  Russian Revolution|1917|         Russia| Revolution|             9.5|
| 17|Black Death Pandemic|1347|         Europe|     Health|             9.3|
| 18|Independence of I...|1947|          India|   Politics|             9.1|
| 19|September 11 Attacks|2001|  United States|  Terrorism|             9.4|
| 20|COVID-19 Pandemic...|2020|         Global|     Health|             9.9|
+---+--------------------+----+---------------+-----------+----------------+
only showing top 20 rows

In [30]:
# Exportar los datos de MariaDB a CSV en data/processed/
db_df.to_csv("../data/processed/historical_events.csv", index=False)
print("✅ CSV guardado en data/processed/historical_events.csv")

✅ CSV guardado en data/processed/historical_events.csv

In [37]:
import pandas as pd

# Leer archivo CSV desde carpeta local
df = pd.read_csv("../data/processed/car_brands.csv")

# Mostrar primeras filas
df.head()

       brand  country  rating  sales_2025 electric_model
0     Toyota    Japan     9.5      850000            Yes
1      Tesla      USA     9.8      620000            Yes
2        BMW  Germany     9.2      410000            Yes
3       Ford      USA     8.7      500000            Yes
4  Chevrolet      USA     8.5      430000             No

In [38]:
print("Cantidad de marcas:", len(df))
print("\nColumnas disponibles:")
print(df.columns)

Cantidad de marcas: 15

Columnas disponibles:
Index(['brand', 'country', 'rating', 'sales_2025', 'electric_model'], dtype='str')

In [39]:
best_rating = df.loc[df['rating'].idxmax()]

print("La marca con mejor rating es:")
print(best_rating['brand'])
print("Rating:", best_rating['rating'])

La marca con mejor rating es:
Ferrari
Rating: 9.9

In [40]:
best_sales = df.loc[df['sales_2025'].idxmax()]

print("La marca con más ventas es:")
print(best_sales['brand'])
print("Ventas:", best_sales['sales_2025'])

La marca con más ventas es:
Toyota
Ventas: 850000

In [41]:
electric = df[df['electric_model'] == 'Yes']

print("Marcas con modelos eléctricos:")
print(electric[['brand', 'country']])

Marcas con modelos eléctricos:
            brand      country
0          Toyota        Japan
1           Tesla          USA
2             BMW      Germany
3            Ford          USA
5         Hyundai  South Korea
6   Mercedes-Benz      Germany
7             Kia  South Korea
10           Audi      Germany
11          Honda        Japan
12         Nissan        Japan
13        Porsche      Germany
14          Volvo       Sweden

In [ ]:
import matplotlib.pyplot as plt

plt.figure(figsize=(10,5))
plt.bar(df['brand'], df['rating'])

plt.xticks(rotation=45)
plt.title("Rating de marcas de carros")
plt.xlabel("Marca")
plt.ylabel("Rating")

plt.show()